package com.chat.androidclient.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chat.androidclient.mvvm.model.Conversation;
import com.chat.androidclient.mvvm.model.Group;
import com.chat.androidclient.mvvm.procotol.response.MessageResponse;
import com.chat.androidclient.mvvm.model.Contact;

import com.chat.androidclient.greendao.ConversationDao;
import com.chat.androidclient.greendao.GroupDao;
import com.chat.androidclient.greendao.MessageResponseDao;
import com.chat.androidclient.greendao.ContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig conversationDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig messageResponseDaoConfig;
    private final DaoConfig contactDaoConfig;

    private final ConversationDao conversationDao;
    private final GroupDao groupDao;
    private final MessageResponseDao messageResponseDao;
    private final ContactDao contactDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        messageResponseDaoConfig = daoConfigMap.get(MessageResponseDao.class).clone();
        messageResponseDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        conversationDao = new ConversationDao(conversationDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        messageResponseDao = new MessageResponseDao(messageResponseDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);

        registerDao(Conversation.class, conversationDao);
        registerDao(Group.class, groupDao);
        registerDao(MessageResponse.class, messageResponseDao);
        registerDao(Contact.class, contactDao);
    }
    
    public void clear() {
        conversationDaoConfig.clearIdentityScope();
        groupDaoConfig.clearIdentityScope();
        messageResponseDaoConfig.clearIdentityScope();
        contactDaoConfig.clearIdentityScope();
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public MessageResponseDao getMessageResponseDao() {
        return messageResponseDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

}
