package com.chat.androidclient.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chat.androidclient.mvvm.model.MessageResponse;
import com.chat.androidclient.mvvm.model.Conversation;

import com.chat.androidclient.greendao.MessageResponseDao;
import com.chat.androidclient.greendao.ConversationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageResponseDaoConfig;
    private final DaoConfig conversationDaoConfig;

    private final MessageResponseDao messageResponseDao;
    private final ConversationDao conversationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageResponseDaoConfig = daoConfigMap.get(MessageResponseDao.class).clone();
        messageResponseDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        messageResponseDao = new MessageResponseDao(messageResponseDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);

        registerDao(MessageResponse.class, messageResponseDao);
        registerDao(Conversation.class, conversationDao);
    }
    
    public void clear() {
        messageResponseDaoConfig.clearIdentityScope();
        conversationDaoConfig.clearIdentityScope();
    }

    public MessageResponseDao getMessageResponseDao() {
        return messageResponseDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

}
